# Generated by Django 5.1.7 on 2025-05-10 03:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_server', '0044_myuser_otp_myuser_otp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpcentremessage',
            name='thread_number',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='workouttype',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
